[package]
name = "oxia-client-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13"
prost = "0.13"
prost-types = "0.14"
tokio = { version = "1.47.0", features = ["rt-multi-thread", "macros"] }
thiserror = "2.0.12"
backon = "1.5.1"
dashmap = "6.1.0"
xxhash-rust = { version = "0.8.5", features = ["xxh32", "const_xxh32"] }
uuid = { version = "1.7", features = ["v4"] }
num_cpus = "1.16"

[build-dependencies]
tonic-build = "0.13.1"